export enum ActionTypes {
  SET_USER_QUERY = 'SET_USER_QUERY',
  SET_ARTICLE_STATE = 'SET_ARTICLE_STATE',
  SET_IS_NOT_FOUND = 'SET_IS_NOT_FOUND',
  SET_SORT_STATE = 'SET_SORT_STATE',
  SET_TOTAL_ITEMS = 'SET_TOTAL_ITEMS',
  NEXT_PAGE = 'NEXT_PAGE',
  PREV_PAGE = 'PREV_PAGE',
  SET_PAGE = 'SET_PAGE',
  SET_INTERSECTION_ELEMENTS = 'SET_INTERSECTION_ELEMENTS',
  SET_IS_SEARCH_LOADING = 'SET_IS_SEARCH_LOADING',
  SET_IS_SEARCH_ACTIVE = 'SET_IS_SEARCH_ACTIVE',
}
